spring:
  application:
    name: book_tracker_api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000000

logging:
  pattern:
    console: "<%green(%d{yy-MM-dd HH:mm:ss}) %highlight(%-5level) %cyan(%logger{10})> %highlight(%msg%n)"
