package dev.wayron.book_tracker_api.modules.exceptions.reading

import dev.wayron.book_tracker_api.modules.exceptions.ExceptionErrorMessages
import java.lang.IllegalStateException

class ReadingSessionCompletedException : IllegalStateException(ExceptionErrorMessages.READING_ALREADY_FINISHED.message)