package dev.wayron.book_tracker_api.modules.exceptions.reading

import dev.wayron.book_tracker_api.modules.exceptions.ExceptionErrorMessages
import jakarta.persistence.EntityNotFoundException

class ReadingSessionNotFoundException : EntityNotFoundException(ExceptionErrorMessages.READING_NOT_FOUND.message)