CREATE TABLE users (
  id VARCHAR(22) PRIMARY KEY,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  profile_image TEXT,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(150) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);